### ISSUE TITLE
Update calibration.city with the last 150 days of prediction data

### ISSUE THREAD

**Issue by justicehoward** [wasabipesto/themis#10]
this is my first GitHub issue. Hope I am not being rude.

**Comment by wasabipesto** [comment]
Not rude, it's a known issue on my priority list. I need to incorporate some API changes before I can update the data.

**Comment by wasabipesto** [comment]
Polymarket and Manifold are updated. Kalshi and Metaculus will require a bit more work.

**Comment by wasabipesto** [comment]
Metaculus is loaded and Kalshi is loading in (slowly) now.
